[0m20:53:32.257587 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A527A1C050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A527A1C2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A5281F3910>]}


============================== 20:53:32.260595 | 4781fee1-46e8-40c3-b6e3-22fc5fecc952 ==============================
[0m20:53:32.260595 [info ] [MainThread]: Running with dbt=1.7.1
[0m20:53:32.261594 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\nikit\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init dbt_hol', 'send_anonymous_usage_stats': 'True'}
[0m20:53:32.262598 [debug] [MainThread]: Starter project path: C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m20:53:32.277904 [info ] [MainThread]: 
Your new dbt project "dbt_hol" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:53:32.279940 [info ] [MainThread]: Setting up your profile.
[0m20:58:06.728423 [error] [MainThread]: Encountered an error:

[0m20:58:06.757662 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 165, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 131, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m20:58:06.763630 [debug] [MainThread]: Command `dbt init` failed at 20:58:06.763630 after 274.55 seconds
[0m20:58:06.763630 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A527CD1890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A52819E3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A5279F8150>]}
[0m20:58:06.764663 [debug] [MainThread]: Flushing usage events
